// Mask Path Tasks
// All tasks unlocked by "Choose the Mask" or requiring Mask path tasks

const maskTasks = [
  { 
    name: "Assume White Mask", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Enter City Temple"], 
    requires: ["Choose the Mask"], 
    cost: { knowledge: 4 },
    yields: { influence: 5 }, 
    description: "Learn to breathe through porcelain stillness, adopting a new name fit for temple halls.", 
    notorietyCost: 6 
  },
  { 
    name: "Serve Soup Lines", 
    baseTime: 6, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { influence: 4, knowledge: 1 },
    description: "Hand out bowls in the temple kitchens, trading mercy for whispers.", 
    unlocked: false, 
    unlockTask: "Assume White Mask", 
    notorietyCost: 4, 
    safe: true, 
    autoRepeat: false 
  },
  { 
    name: "Forge False Papers", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Enter City Temple"], 
    requires: ["Assume White Mask"], 
    cost: { influence: 4 }, 
    yields: { secrets: 3 }, 
    description: "Craft identities that survive temple scrutiny, broadening your cover.", 
    resourceMaxIncrease: { influence: 10, secrets: 5 }, 
    notorietyCost: 6 
  },
  { 
    name: "Spin Market Rumors", 
    baseTime: 6, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { rumors: 4, influence: 1, knowledge: 1 },
    description: "Feed the bazaar with slanted tales that boost your rumor stockpile.", 
    unlocked: false, 
    unlockTask: "Assume White Mask", 
    notorietyCost: 6, 
    autoRepeat: false 
  },
  { 
    name: "Enter City Temple", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Mimic Liturgies", "Whisper Doubt"], 
    requires: ["Assume White Mask"], 
    cost: { influence: 4, knowledge: 3 },
    yields: { influence: 4 }, 
    description: "Walk among the faithful, mapping their routines and their blind spots beneath stained glass.", 
    notorietyCost: 8 
  },
  { 
    name: "Trade Choir Secrets", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { influence: 3, evidence: 2, knowledge: 1 },
    description: "Swap rumors with choristers during rehearsals, weaving doubt into the verses.", 
    unlocked: false, 
    unlockTask: "Enter City Temple", 
    notorietyCost: 6, 
    autoRepeat: false 
  },
  { 
    name: "Bribe City Clerk", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Mimic Liturgies", "Whisper Doubt"], 
    requires: ["Enter City Temple"], 
    cost: { influence: 6, secrets: 3 }, 
    yields: { secrets: 4, influence: 2 }, 
    description: "Purchase access ledgers and service rosters, deepening your reach inside the temple.", 
    resourceMaxIncrease: { influence: 10, secrets: 5 }, 
    notorietyCost: 9 
  },
  { 
    name: "Deepen Cover Identities", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Sow Rot in Choir"], 
    requires: ["Bribe City Clerk"], 
    cost: { covers: 4, influence: 4 }, 
    yields: { covers: 2, secrets: 2 }, 
    description: "Layer new identities atop old ones, broadening how much influence you can safely carry.", 
    resourceMaxIncrease: { covers: 6, influence: 6 }, 
    notorietyCost: 10 
  },
  { 
    name: "Mimic Liturgies", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Sow Rot in Choir"], 
    requires: ["Enter City Temple"], 
    cost: { influence: 4, knowledge: 4 }, 
    yields: { influence: 5 }, 
    description: "Perfect the cadence of prayers to earn deeper access, wearing piety like a borrowed robe.", 
    notorietyCost: 7 
  },
  { 
    name: "Whisper Doubt", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Fracture Congregation"], 
    requires: ["Enter City Temple"], 
    cost: { influence: 5 }, 
    yields: { influence: 3 }, 
    description: "Seed quiet questions in confession lines, loosening the mortar of belief one listener at a time.", 
    notorietyCost: 9 
  },
  { 
    name: "Sow Rot in Choir", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Fracture Congregation"], 
    requires: ["Mimic Liturgies"], 
    cost: { influence: 6, knowledge: 4 }, 
    yields: { influence: 4 }, 
    description: "Twist hymns into double-meanings that erode faith from within the music itself.", 
    notorietyCost: 10 
  },
  { 
    name: "Fracture Congregation", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Whisper Doubt", "Sow Rot in Choir"], 
    cost: { influence: 8, knowledge: 6 }, 
    yields: { evidence: 3 }, 
    description: "Witness factions form inside the temple; harvest their confessions as proof of divine neglect.", 
    notorietyCost: 14 
  }
];
