// Scholar Path Tasks
// All tasks unlocked by "Choose the Book" or requiring Scholar path tasks

const scholarTasks = [
  { 
    name: "Collect Abandoned Scrolls", 
    baseTime: 6, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { scrolls: 2, evidence: 1, knowledge: 1 },
    description: "Scour ruined huts for discarded scrolls, stockpiling fuel for scholarship.", 
    unlocked: false, 
    unlockTask: "Choose the Book", 
    resourceMaxIncrease: { scrolls: 4 }, 
    safe: true, 
    autoRepeat: false 
  },
  { 
    name: "Scholar of Silence", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Calavan Library"], 
    requires: ["Choose the Book"], 
    cost: { knowledge: 4 },
    yields: { evidence: 2 }, 
    description: "Embrace the Canticle's thesis: death is the only constant and gods are parasites; you set out to prove it.", 
    notorietyCost: 6 
  },
  { 
    name: "Annotate Canticle Margins", 
    baseTime: 6, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { insight: 3, evidence: 1, knowledge: 1 },
    description: "Scrawl notes between forbidden lines, sharpening the logic of death.", 
    unlocked: false, 
    unlockTask: "Scholar of Silence", 
    resourceMaxIncrease: { insight: 5 }, 
    safe: true, 
    autoRepeat: false 
  },
  { 
    name: "Copy Dusty Scrolls", 
    baseTime: 6, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { knowledge: 4, evidence: 2 }, 
    description: "Meticulously copy brittle scrolls, compiling cases of divine neglect.", 
    unlocked: false, 
    unlockTask: "Scholar of Silence", 
    safe: true, 
    autoRepeat: false 
  },
  { 
    name: "Calavan Library", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Historian's Case", "Map Necrotic Equations", "Practice Forbidden Annex"], 
    requires: ["Scholar of Silence"], 
    cost: { mana: 5, knowledge: 5 }, 
    yields: { knowledge: 3, evidence: 2 }, 
    description: "Enter the decaying stacks of Calavan where dust thickens on heresy and the air hums with suppressed truths.", 
    notorietyCost: 4 
  },
  { 
    name: "Bind Proof Codex", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Historian's Case", "Map Necrotic Equations"], 
    requires: ["Calavan Library"], 
    cost: { knowledge: 6, evidence: 4 }, 
    yields: { evidence: 3 }, 
    description: "Stitch gathered claims into a single codex, expanding your ability to hold damning proof.", 
    resourceMaxIncrease: { evidence: 10 }, 
    notorietyCost: 6 
  },
  { 
    name: "Restore Grimoire Bindings", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Collect Field Fragments"], 
    requires: ["Bind Proof Codex"], 
    cost: { knowledge: 6, evidence: 2 }, 
    yields: { grimoires: 1 }, 
    description: "Rebind cracked grimoires so their power can expand your mental vaults.", 
    resourceMaxIncrease: { grimoires: 2, knowledge: 5 }, 
    notorietyCost: 8 
  },
  { 
    name: "Collect Field Fragments", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Historian's Case", "Map Necrotic Equations"], 
    requires: ["Restore Grimoire Bindings"], 
    cost: { mana: 6 }, 
    yields: { scrolls: 2, evidence: 1 }, 
    description: "Gather torn pages from roadside shrines and battlefields, feeding your growing archive.", 
    resourceMaxIncrease: { scrolls: 4 }, 
    notorietyCost: 6 
  },
  { 
    name: "Debate Archivist", 
    baseTime: 7, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    repeatable: true, 
    yields: { evidence: 3, influence: 1, knowledge: 1 },
    description: "Corner tired archivists into late-night debates, extracting admissions of unanswered prayers.", 
    unlocked: false, 
    unlockTask: "Calavan Library", 
    safe: true, 
    autoRepeat: false 
  },
  { 
    name: "Historian's Case", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Field of Weeping Spears", "Cathedral of the Dawn"], 
    requires: ["Calavan Library"], 
    cost: { knowledge: 6 }, 
    yields: { evidence: 4 }, 
    description: "Dig through archives for plagues ignored, covenants broken, and the God-Butchering Heresy whispered in footnotes.", 
    notorietyCost: 7, 
    choiceGroup: "ScholarBranch", 
    choiceKey: "Historian", 
    choiceParentGroup: "SeedChoice", 
    choiceParentKey: "Book" 
  },
  { 
    name: "Field of Weeping Spears", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Mercenary Company", "Whisper with Ghosts"], 
    requires: ["Historian's Case"], 
    cost: { mana: 8, knowledge: 4 }, 
    yields: { evidence: 2, fury: 2 }, 
    description: "Travel to the haunted battlefield where a heretic-general was entombed with a fragment of forbidden proof.", 
    notorietyCost: 12, 
    choiceGroup: "HistorianSplit", 
    choiceKey: "Battlefield", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Historian" 
  },
  { 
    name: "Cathedral of the Dawn", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Feign Acolyte", "Cat Burglar's Plot"], 
    requires: ["Historian's Case"], 
    cost: { mana: 6, knowledge: 6 }, 
    yields: { influence: 2, evidence: 2 }, 
    description: "Slip toward the radiant cathedral vaults where another fragment lies hidden among relics and hymns.", 
    notorietyCost: 9, 
    choiceGroup: "HistorianSplit", 
    choiceKey: "Cathedral", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Historian" 
  },
  { 
    name: "Mercenary Company", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Claim Battlefield Fragment"], 
    requires: ["Field of Weeping Spears"], 
    cost: { mana: 10 }, 
    yields: { fury: 4 }, 
    description: "Join a rough company to cut through the no-man's-land, trading ideals for tactics and scars.", 
    notorietyCost: 16 
  },
  { 
    name: "Whisper with Ghosts", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Claim Battlefield Fragment"], 
    requires: ["Field of Weeping Spears"], 
    cost: { mana: 8, knowledge: 4 }, 
    yields: { evidence: 3 }, 
    description: "Coax spectral guides from the spears, bargaining with the dead to reach the heretic's tomb unseen.", 
    notorietyCost: 13 
  },
  { 
    name: "Claim Battlefield Fragment", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Mercenary Company", "Whisper with Ghosts"], 
    cost: { mana: 10, knowledge: 6 }, 
    yields: { evidence: 5 }, 
    description: "Prise the God-Butchering fragment from rust and bone, feeling it hum with arguments that could sever faith.", 
    notorietyCost: 12 
  },
  { 
    name: "Feign Acolyte", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Steal Cathedral Fragment"], 
    requires: ["Cathedral of the Dawn"], 
    cost: { knowledge: 8 }, 
    yields: { influence: 3 }, 
    description: "Don robes and prayers, mimicking devotion to infiltrate the vaults from within the choir.", 
    notorietyCost: 8 
  },
  { 
    name: "Cat Burglar's Plot", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Steal Cathedral Fragment"], 
    requires: ["Cathedral of the Dawn"], 
    cost: { mana: 8 }, 
    yields: { influence: 2 }, 
    description: "Map guards and locks, readying a silent heist to lift the fragment without ever uttering a psalm.", 
    notorietyCost: 9 
  },
  { 
    name: "Steal Cathedral Fragment", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Feign Acolyte", "Cat Burglar's Plot"], 
    cost: { mana: 10, knowledge: 6, influence: 4 }, 
    yields: { evidence: 5 }, 
    description: "Slip into the Dawn vaults and lift the heresy fragment, heart pounding beneath stained glass.", 
    notorietyCost: 14 
  },
  { 
    name: "Map Necrotic Equations", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Collapse Souls", "Seek Dead World"], 
    requires: ["Calavan Library"], 
    cost: { knowledge: 8 }, 
    yields: { evidence: 3 }, 
    description: "Pursue the Canticle's math: death as cosmic grammar, leading to the need for a Necrotic Singularity.", 
    notorietyCost: 9, 
    choiceGroup: "ScholarBranch", 
    choiceKey: "Equations", 
    choiceParentGroup: "SeedChoice", 
    choiceParentKey: "Book" 
  },
  { 
    name: "Model Death Equation", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Collapse Souls", "Seek Dead World"], 
    requires: ["Map Necrotic Equations"], 
    cost: { insight: 6, knowledge: 6 }, 
    yields: { insight: 4 }, 
    description: "Iterate metaphysical models until the grammar of endings coheres.", 
    resourceMaxIncrease: { insight: 10 }, 
    notorietyCost: 10 
  },
  { 
    name: "Synthesize Axiom Primer", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Collapse Souls", "Seek Dead World"], 
    requires: ["Model Death Equation"], 
    cost: { insight: 8, scrolls: 4 }, 
    yields: { insight: 3, evidence: 2 }, 
    description: "Draft a primer that ties field fragments to the Axiom, widening your mental channels.", 
    resourceMaxIncrease: { insight: 6, scrolls: 2 }, 
    notorietyCost: 11 
  },
  { 
    name: "Collapse Souls", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Target Penal Colony", "Target Asylum"], 
    requires: ["Map Necrotic Equations"], 
    cost: { mana: 12, knowledge: 6 }, 
    description: "Plot a ritual to crush hundreds of souls together, a monstrous shortcut toward singularity.", 
    notorietyCost: 20, 
    choiceGroup: "EquationSplit", 
    choiceKey: "Collapse", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Equations" 
  },
  { 
    name: "Seek Dead World", 
    baseTime: 10, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Recruit Stonesailor", "Build Void Compass"], 
    requires: ["Map Necrotic Equations"], 
    cost: { mana: 10, knowledge: 6 }, 
    yields: { evidence: 2 }, 
    description: "Chase legends of a natural Necrotic Singularity in the Heart of the Dead World.", 
    notorietyCost: 11, 
    choiceGroup: "EquationSplit", 
    choiceKey: "SeekDeadWorld", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Equations" 
  },
  { 
    name: "Target Penal Colony", 
    baseTime: 11, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Collapse Souls"], 
    cost: { mana: 12, knowledge: 8 }, 
    description: "Mark a remote prison as fodder, telling yourself the guilty will fuel your singularity.", 
    notorietyCost: 18, 
    choiceGroup: "CollapseTarget", 
    choiceKey: "Prison", 
    choiceParentGroup: "EquationSplit", 
    choiceParentKey: "Collapse" 
  },
  { 
    name: "Target Asylum", 
    baseTime: 11, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Collapse Souls"], 
    cost: { mana: 12, knowledge: 8 }, 
    description: "Fixate on a forgotten sanatorium, convincing yourself that ending their suffering serves your cause.", 
    notorietyCost: 18, 
    choiceGroup: "CollapseTarget", 
    choiceKey: "Asylum", 
    choiceParentGroup: "EquationSplit", 
    choiceParentKey: "Collapse" 
  },
  { 
    name: "Recruit Stonesailor", 
    baseTime: 11, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Seek Dead World"], 
    cost: { mana: 10, knowledge: 10 }, 
    yields: { evidence: 2 }, 
    description: "Persuade the last Stonesailor to guide you across lifeless seas toward the Dead World.", 
    notorietyCost: 12, 
    choiceGroup: "DeadWorldRoute", 
    choiceKey: "Guide", 
    choiceParentGroup: "EquationSplit", 
    choiceParentKey: "SeekDeadWorld" 
  },
  { 
    name: "Build Void Compass", 
    baseTime: 11, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Seek Dead World"], 
    cost: { mana: 14, knowledge: 10 }, 
    yields: { evidence: 2 }, 
    description: "Forge a metaphysical compass to tear a passage toward the Dead World, risking attention from stranger voids.", 
    notorietyCost: 13, 
    choiceGroup: "DeadWorldRoute", 
    choiceKey: "Compass", 
    choiceParentGroup: "EquationSplit", 
    choiceParentKey: "SeekDeadWorld" 
  },
  { 
    name: "Practice Forbidden Annex", 
    baseTime: 8, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Answer Lich Xyros", "Defy Dawn Inquisitor"], 
    requires: ["Calavan Library"], 
    cost: { mana: 6, knowledge: 6 }, 
    yields: { evidence: 2 }, 
    description: "Skim the margins of the Canticle, animating rats and whispering with nearby ghosts until eyes take notice.", 
    notorietyCost: 11, 
    choiceGroup: "ScholarBranch", 
    choiceKey: "Annex", 
    choiceParentGroup: "SeedChoice", 
    choiceParentKey: "Book" 
  },
  { 
    name: "Answer Lich Xyros", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Practice Forbidden Annex"], 
    cost: { mana: 10, knowledge: 8 }, 
    yields: { evidence: 2 }, 
    description: "Accept the phylactery's summons to apprentice under lich Xyros, trading freedom for structured power.", 
    notorietyCost: 14, 
    choiceGroup: "AnnexSplit", 
    choiceKey: "Xyros", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Annex" 
  },
  { 
    name: "Defy Dawn Inquisitor", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Slay the Inquisitor", "Corrupt the Inquisitor"], 
    requires: ["Practice Forbidden Annex"], 
    cost: { mana: 8, knowledge: 6 }, 
    description: "An inquisitor arrives; you must decide whether to end or bend this hunter.", 
    notorietyCost: 13, 
    choiceGroup: "AnnexSplit", 
    choiceKey: "Inquisitor", 
    choiceParentGroup: "ScholarBranch", 
    choiceParentKey: "Annex" 
  },
  { 
    name: "Slay the Inquisitor", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Defy Dawn Inquisitor"], 
    cost: { mana: 10 }, 
    yields: { fury: 3 }, 
    description: "Strike first and silence the Dawn's investigator, accepting the price of becoming a hunted killer.", 
    notorietyCost: 20, 
    choiceGroup: "InquisitorOutcome", 
    choiceKey: "Slay", 
    choiceParentGroup: "AnnexSplit", 
    choiceParentKey: "Inquisitor" 
  },
  { 
    name: "Corrupt the Inquisitor", 
    baseTime: 9, 
    proficiency: 0, 
    isActive: false, 
    completed: false, 
    unlocks: ["Axiom of Unmaking"], 
    requires: ["Defy Dawn Inquisitor"], 
    cost: { mana: 8, knowledge: 8 }, 
    yields: { influence: 3 }, 
    description: "Show the inquisitor a vision of divine betrayal, wagering you can twist a zealot into an unwilling ally.", 
    notorietyCost: 14, 
    choiceGroup: "InquisitorOutcome", 
    choiceKey: "Corrupt", 
    choiceParentGroup: "AnnexSplit", 
    choiceParentKey: "Inquisitor" 
  }
];
